// AUTO-GENERATED by the Morphivore agent crew. Do not edit by hand.
// Loads output/forms.json (the 150 authored Bestiary forms) into typed structs.
using System;
using UnityEngine;

namespace Morphivore.Content
{
    [Serializable]
    public class StatBlock
    {
        public float health;
        public float damage;
        public float speed;
        public float reach;
        public float dash;
    }

    [Serializable]
    public class FormDef
    {
        public string id;
        public string family;
        public string @class;      // serialises as "class"
        public string intensity;
        public int intensity_pct;
        public int rank;
        public string name;
        public string flavor;
        public string base_hex;
        public float saturation;
        public string silhouette;
        public string surface;
        public string vfx;
        public string[] socket_layout;
        public StatBlock stats;
    }

    [Serializable]
    public class FormTable
    {
        public string generated_by;
        public int count;
        public FormDef[] forms;

        /// <summary>Parse the crew's forms.json (root object with a "forms" array).</summary>
        public static FormTable Load(string json) => JsonUtility.FromJson<FormTable>(json);
    }
}
