// AUTO-GENERATED by the Morphivore world-content crew. Do not edit by hand.
// Loads creatures.json / panels.json / biomes.json into typed structs.
using System;
using UnityEngine;

namespace Morphivore.Content
{
    [Serializable] public class CreatureStats { public float health; public float damage;
        public float speed; public float reach; public float dash; }

    [Serializable] public class SpawnDef { public string biome; public int rank;
        public bool pocket_only; public float flee_speed; public CreatureStats stats; }

    [Serializable] public class CreatureDef
    {
        public string id, role, name, flavor, family, @class, tier, base_hex;
        public string grants_trait, opens, habitat;
        public int rank, limbs;
        public float saturation, heals_player_pct;
        public bool carries_colour, counts_toward_alpha_gate, drops_panels;
        public bool drops_emblem, emblem_grants_power, can_be_outrun, flees;
        public SpawnDef[] spawns;
    }

    [Serializable] public class PanelDef
    {
        public string id, name, flavor, power, power_description, attach, dropped_by;
        public float magnitude;
        public bool stacks, survives_mutation, survives_breeding;
    }

    [Serializable] public class GateDef { public int distinct_forms_required;
        public int coloured_prey_required; }

    // palette_weights is keyed by family in JSON. JsonUtility can't deserialise a
    // dictionary, but the family set is fixed by the world contract, so declaring
    // one field per family reads the same object with no reshaping of the content.
    [Serializable] public class PaletteWeights
    {
        public float Yellow, Red, Blue, Purple, Grey;
        public float For(string family) => family switch
        {
            "Yellow" => Yellow, "Red"  => Red,  "Blue" => Blue,
            "Purple" => Purple, "Grey" => Grey, _      => 0f
        };
    }

    [Serializable] public class BiomeDef
    {
        public string id, name, terrain, entrance, deep_end, alpha_lair;
        public int order, player_rank, min_distinct_colours, standing_population;
        public float respawn_per_min;
        public string[] gates_requiring_traits, traits_introduced;
        public string[] wandering_tiers, pocket_tiers, pockets, alpha_roster;
        public PaletteWeights palette_weights;
        public GateDef gates;
    }

    [Serializable] public class CreatureTable { public int count; public bool lore_verified;
        public CreatureDef[] creatures;
        public static CreatureTable Load(string json) => JsonUtility.FromJson<CreatureTable>(json); }

    [Serializable] public class PanelTable { public int count; public bool lore_verified;
        public PanelDef[] panels;
        public static PanelTable Load(string json) => JsonUtility.FromJson<PanelTable>(json); }

    [Serializable] public class BiomeTable { public int count; public bool lore_verified;
        public BiomeDef[] biomes;
        public static BiomeTable Load(string json) => JsonUtility.FromJson<BiomeTable>(json); }
}
